add solution for lecture-3 02-modal
js-tasks-ru/htmlcss-20230714_ilya-kotov2 pull request #11
Opened 2023-08-01 07:29 UTC by dsv43b

2023-08-01 07:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-08-01 21:08 UTC, GSemikozov requested changes

2023-08-01 21:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
6-12 строчки уносим на .modal, фон - через rgba, background удаляем

2023-08-01 21:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    margin: 40px 40px 47px;
марджины не нужны

2023-08-02 14:37 UTC, dsv43b commented
Исправил ошибки

2023-08-04 07:00 UTC, GSemikozov approved these changes

2023-08-04 07:01 UTC, merged