add solution for lecture-1 02-accordion
js-tasks-ru/htmlcss-20230714_ilya-kotov2 pull request #7
Opened 2023-07-26 15:50 UTC by dsv43b

2023-07-26 15:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-27 11:58 UTC, GSemikozov requested changes

2023-07-27 11:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ширину ограничивать не нужно

2023-07-27 11:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
все остальные свойства - это часть .accordion__item, поскольку мы верстаем 1 аккордион, у которого 3 секции, а не 3 отдельных аккордиона у которых по 1 секции

2023-07-27 11:58 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
и еще при .accordion__item[open] padding-bottom: 32px

2023-07-27 11:58 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +  <section class="section">
section не надо, и класс блока здесь - .accordion

2023-07-27 11:58 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__item" open>
использовать класс блока и класс элемента этого блока на одном уровне - большая ошибка, точно так же как отец не может быть одновременно своим ребенком

2023-07-27 11:58 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion accordion__item" open>
здесь должен быть лишь класс элемента

2023-07-29 08:44 UTC, dsv43b commented
Исправил ошибки.

2023-07-29 11:04 UTC, GSemikozov approved these changes

2023-07-29 11:04 UTC, merged