add solution for lecture-2 02-skeleton
js-tasks-ru/htmlcss-20230714_ilya-kotov2 pull request #9
Opened 2023-07-28 10:40 UTC by dsv43b

2023-07-28 10:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-28 14:54 UTC, GSemikozov requested changes

2023-07-28 14:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px;
снизу 32)

2023-07-28 14:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_top {
.skeleton__top

2023-07-28 14:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 200px;
лишнее

2023-07-28 14:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px
ширину лучше в процентах, можно просто приблизительно

2023-07-28 14:54 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_length_s {
.skeleton__text_length_s

2023-07-29 08:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-29 08:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-29 09:28 UTC, dsv43b commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_top {
Опечатался, спасибо.

2023-07-29 09:29 UTC, dsv43b commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 200px;
Здесь не понял, что именно лишнее?

2023-07-29 11:05 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 200px;
width: 200px;

2023-07-29 12:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-29 12:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-30 20:32 UTC, GSemikozov approved these changes

2023-07-30 20:32 UTC, merged